//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgUplCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}OrgOgzCnyCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}OrgOgzNr" minOccurs="0"/>
 *         &lt;element name="DelSraCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RslCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShrIdInfTe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShrNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DvrNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DvrEmpIdNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DvrFupReqIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LdUntNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LopNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CnsNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MunNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MunSdvNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}SecUnt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CtgIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DelAtpCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpStrNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpStrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpStrPfxNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpStrSufNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpStrTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpPriPslCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StpSecPslCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SigLstNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}DatCpMthCgyCd"/>
 *       &lt;attribute ref="{upscm}DatCpInfSrcCd"/>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgUplCd",
    "orgOgzCnyCd",
    "orgOgzNr",
    "delSraCd",
    "rslCd",
    "shrIdInfTe",
    "shrNa",
    "dvrNa",
    "dvrEmpIdNr",
    "dvrFupReqIr",
    "ldUntNr",
    "lopNr",
    "cnsNa",
    "munNa",
    "munSdvNa",
    "secUnt",
    "ctgIr",
    "delAtpCd",
    "stpStrNa",
    "stpStrNr",
    "stpStrPfxNa",
    "stpStrSufNa",
    "stpStrTypCd",
    "stpPriPslCd",
    "stpSecPslCd",
    "sigLstNa"
})
@XmlRootElement(name = "DelAcy")
@JsonInclude(Include.NON_NULL)
public class DelAcy {

    @XmlElement(name = "MsgUplCd")
    protected String msgUplCd;
    @XmlElement(name = "OrgOgzCnyCd", namespace = "upscm")
    protected String orgOgzCnyCd;
    @XmlElement(name = "OrgOgzNr", namespace = "upscm")
    protected String orgOgzNr;
    @XmlElement(name = "DelSraCd")
    protected String delSraCd;
    @XmlElement(name = "RslCd")
    protected String rslCd;
    @XmlElement(name = "ShrIdInfTe")
    protected String shrIdInfTe;
    @XmlElement(name = "ShrNa")
    protected String shrNa;
    @XmlElement(name = "DvrNa")
    protected String dvrNa;
    @XmlElement(name = "DvrEmpIdNr")
    protected String dvrEmpIdNr;
    @XmlElement(name = "DvrFupReqIr")
    protected Boolean dvrFupReqIr;
    @XmlElement(name = "LdUntNr")
    protected String ldUntNr;
    @XmlElement(name = "LopNr")
    protected String lopNr;
    @XmlElement(name = "CnsNa")
    protected String cnsNa;
    @XmlElement(name = "MunNa")
    protected String munNa;
    @XmlElement(name = "MunSdvNa")
    protected String munSdvNa;
    @XmlElement(name = "SecUnt", namespace = "upscm")
    protected List<SecUnt> secUnt;
    @XmlElement(name = "CtgIr")
    protected Boolean ctgIr;
    @XmlElement(name = "DelAtpCd")
    protected String delAtpCd;
    @XmlElement(name = "StpStrNa")
    protected String stpStrNa;
    @XmlElement(name = "StpStrNr")
    protected String stpStrNr;
    @XmlElement(name = "StpStrPfxNa")
    protected String stpStrPfxNa;
    @XmlElement(name = "StpStrSufNa")
    protected String stpStrSufNa;
    @XmlElement(name = "StpStrTypCd")
    protected String stpStrTypCd;
    @XmlElement(name = "StpPriPslCd")
    protected String stpPriPslCd;
    @XmlElement(name = "StpSecPslCd")
    protected String stpSecPslCd;
    @XmlElement(name = "SigLstNa")
    protected String sigLstNa;
    @XmlAttribute(name = "DatCpMthCgyCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpMthCgyCd;
    @XmlAttribute(name = "DatCpInfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpInfSrcCd;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the msgUplCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgUplCd() {
        return msgUplCd;
    }

    /**
     * Sets the value of the msgUplCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgUplCd(String value) {
        this.msgUplCd = value;
    }

    /**
     * Gets the value of the orgOgzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgOgzCnyCd() {
        return orgOgzCnyCd;
    }

    /**
     * Sets the value of the orgOgzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgOgzCnyCd(String value) {
        this.orgOgzCnyCd = value;
    }

    /**
     * Gets the value of the orgOgzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgOgzNr() {
        return orgOgzNr;
    }

    /**
     * Sets the value of the orgOgzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgOgzNr(String value) {
        this.orgOgzNr = value;
    }

    /**
     * Gets the value of the delSraCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelSraCd() {
        return delSraCd;
    }

    /**
     * Sets the value of the delSraCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelSraCd(String value) {
        this.delSraCd = value;
    }

    /**
     * Gets the value of the rslCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRslCd() {
        return rslCd;
    }

    /**
     * Sets the value of the rslCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRslCd(String value) {
        this.rslCd = value;
    }

    /**
     * Gets the value of the shrIdInfTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShrIdInfTe() {
        return shrIdInfTe;
    }

    /**
     * Sets the value of the shrIdInfTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShrIdInfTe(String value) {
        this.shrIdInfTe = value;
    }

    /**
     * Gets the value of the shrNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShrNa() {
        return shrNa;
    }

    /**
     * Sets the value of the shrNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShrNa(String value) {
        this.shrNa = value;
    }

    /**
     * Gets the value of the dvrNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDvrNa() {
        return dvrNa;
    }

    /**
     * Sets the value of the dvrNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDvrNa(String value) {
        this.dvrNa = value;
    }

    /**
     * Gets the value of the dvrEmpIdNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDvrEmpIdNr() {
        return dvrEmpIdNr;
    }

    /**
     * Sets the value of the dvrEmpIdNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDvrEmpIdNr(String value) {
        this.dvrEmpIdNr = value;
    }

    /**
     * Gets the value of the dvrFupReqIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDvrFupReqIr() {
        return dvrFupReqIr;
    }

    /**
     * Sets the value of the dvrFupReqIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDvrFupReqIr(Boolean value) {
        this.dvrFupReqIr = value;
    }

    /**
     * Gets the value of the ldUntNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdUntNr() {
        return ldUntNr;
    }

    /**
     * Sets the value of the ldUntNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdUntNr(String value) {
        this.ldUntNr = value;
    }

    /**
     * Gets the value of the lopNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLopNr() {
        return lopNr;
    }

    /**
     * Sets the value of the lopNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLopNr(String value) {
        this.lopNr = value;
    }

    /**
     * Gets the value of the cnsNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnsNa() {
        return cnsNa;
    }

    /**
     * Sets the value of the cnsNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnsNa(String value) {
        this.cnsNa = value;
    }

    /**
     * Gets the value of the munNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunNa() {
        return munNa;
    }

    /**
     * Sets the value of the munNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunNa(String value) {
        this.munNa = value;
    }

    /**
     * Gets the value of the munSdvNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunSdvNa() {
        return munSdvNa;
    }

    /**
     * Sets the value of the munSdvNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunSdvNa(String value) {
        this.munSdvNa = value;
    }

    /**
     * Gets the value of the secUnt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secUnt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecUnt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecUnt }
     * 
     * 
     */
    public List<SecUnt> getSecUnt() {
        if (secUnt == null) {
            secUnt = new ArrayList<SecUnt>();
        }
        return this.secUnt;
    }

    /**
     * Gets the value of the ctgIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCtgIr() {
        return ctgIr;
    }

    /**
     * Sets the value of the ctgIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCtgIr(Boolean value) {
        this.ctgIr = value;
    }

    /**
     * Gets the value of the delAtpCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelAtpCd() {
        return delAtpCd;
    }

    /**
     * Sets the value of the delAtpCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelAtpCd(String value) {
        this.delAtpCd = value;
    }

    /**
     * Gets the value of the stpStrNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpStrNa() {
        return stpStrNa;
    }

    /**
     * Sets the value of the stpStrNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpStrNa(String value) {
        this.stpStrNa = value;
    }

    /**
     * Gets the value of the stpStrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpStrNr() {
        return stpStrNr;
    }

    /**
     * Sets the value of the stpStrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpStrNr(String value) {
        this.stpStrNr = value;
    }

    /**
     * Gets the value of the stpStrPfxNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpStrPfxNa() {
        return stpStrPfxNa;
    }

    /**
     * Sets the value of the stpStrPfxNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpStrPfxNa(String value) {
        this.stpStrPfxNa = value;
    }

    /**
     * Gets the value of the stpStrSufNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpStrSufNa() {
        return stpStrSufNa;
    }

    /**
     * Sets the value of the stpStrSufNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpStrSufNa(String value) {
        this.stpStrSufNa = value;
    }

    /**
     * Gets the value of the stpStrTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpStrTypCd() {
        return stpStrTypCd;
    }

    /**
     * Sets the value of the stpStrTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpStrTypCd(String value) {
        this.stpStrTypCd = value;
    }

    /**
     * Gets the value of the stpPriPslCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpPriPslCd() {
        return stpPriPslCd;
    }

    /**
     * Sets the value of the stpPriPslCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpPriPslCd(String value) {
        this.stpPriPslCd = value;
    }

    /**
     * Gets the value of the stpSecPslCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStpSecPslCd() {
        return stpSecPslCd;
    }

    /**
     * Sets the value of the stpSecPslCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStpSecPslCd(String value) {
        this.stpSecPslCd = value;
    }

    /**
     * Gets the value of the sigLstNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigLstNa() {
        return sigLstNa;
    }

    /**
     * Sets the value of the sigLstNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigLstNa(String value) {
        this.sigLstNa = value;
    }

    /**
     * Gets the value of the datCpMthCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpMthCgyCd() {
        return datCpMthCgyCd;
    }

    /**
     * Sets the value of the datCpMthCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpMthCgyCd(String value) {
        this.datCpMthCgyCd = value;
    }

    /**
     * Gets the value of the datCpInfSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpInfSrcCd() {
        return datCpInfSrcCd;
    }

    /**
     * Sets the value of the datCpInfSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpInfSrcCd(String value) {
        this.datCpInfSrcCd = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
