//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for DmnTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DmnTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}MsuMnmTe" minOccurs="0"/>
 *         &lt;element name="LenQy" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="WidQy" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="HtQy" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DmnTyp", propOrder = {
    "msuMnmTe",
    "lenQy",
    "widQy",
    "htQy"
})
@JsonInclude(Include.NON_NULL)
public class DmnTyp {

    @XmlElement(name = "MsuMnmTe", namespace = "upscm")
    protected String msuMnmTe;
    @XmlElement(name = "LenQy")
    protected BigDecimal lenQy;
    @XmlElement(name = "WidQy")
    protected BigDecimal widQy;
    @XmlElement(name = "HtQy")
    protected BigDecimal htQy;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the msuMnmTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsuMnmTe() {
        return msuMnmTe;
    }

    /**
     * Sets the value of the msuMnmTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsuMnmTe(String value) {
        this.msuMnmTe = value;
    }

    /**
     * Gets the value of the lenQy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLenQy() {
        return lenQy;
    }

    /**
     * Sets the value of the lenQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLenQy(BigDecimal value) {
        this.lenQy = value;
    }

    /**
     * Gets the value of the widQy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWidQy() {
        return widQy;
    }

    /**
     * Sets the value of the widQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWidQy(BigDecimal value) {
        this.widQy = value;
    }

    /**
     * Gets the value of the htQy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHtQy() {
        return htQy;
    }

    /**
     * Sets the value of the htQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHtQy(BigDecimal value) {
        this.htQy = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
