//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HzmStsChnIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AudStsCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AudStsTs" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="AurUsrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AirTptAudPsxIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AirTptAudOcrIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CgoArcOlyIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TptMdeCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TunResCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}DatCpMthCgyCd"/>
 *       &lt;attribute ref="{upscm}DatCpInfSrcCd"/>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hzmStsChnIr",
    "audStsCd",
    "audStsTs",
    "aurUsrNr",
    "airTptAudPsxIr",
    "airTptAudOcrIr",
    "cgoArcOlyIr",
    "tptMdeCd",
    "tunResCd"
})
@XmlRootElement(name = "HzmAudAcy")
@JsonInclude(Include.NON_NULL)
public class HzmAudAcy {

    @XmlElement(name = "HzmStsChnIr")
    protected Boolean hzmStsChnIr;
    @XmlElement(name = "AudStsCd")
    protected String audStsCd;
    @XmlElement(name = "AudStsTs")
    @XmlSchemaType(name = "dateTime")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss")
    protected String audStsTs;
    @XmlElement(name = "AurUsrNr")
    protected String aurUsrNr;
    @XmlElement(name = "AirTptAudPsxIr")
    protected Boolean airTptAudPsxIr;
    @XmlElement(name = "AirTptAudOcrIr")
    protected Boolean airTptAudOcrIr;
    @XmlElement(name = "CgoArcOlyIr")
    protected Boolean cgoArcOlyIr;
    @XmlElement(name = "TptMdeCd")
    protected String tptMdeCd;
    @XmlElement(name = "TunResCd")
    protected String tunResCd;
    @XmlAttribute(name = "DatCpMthCgyCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpMthCgyCd;
    @XmlAttribute(name = "DatCpInfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpInfSrcCd;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the hzmStsChnIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHzmStsChnIr() {
        return hzmStsChnIr;
    }

    /**
     * Sets the value of the hzmStsChnIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHzmStsChnIr(Boolean value) {
        this.hzmStsChnIr = value;
    }

    /**
     * Gets the value of the audStsCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudStsCd() {
        return audStsCd;
    }

    /**
     * Sets the value of the audStsCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudStsCd(String value) {
        this.audStsCd = value;
    }

    /**
     * Gets the value of the audStsTs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAudStsTs() {
        return audStsTs;
    }

    /**
     * Sets the value of the audStsTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAudStsTs(String value) {
        this.audStsTs = value;
    }

    /**
     * Gets the value of the aurUsrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAurUsrNr() {
        return aurUsrNr;
    }

    /**
     * Sets the value of the aurUsrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAurUsrNr(String value) {
        this.aurUsrNr = value;
    }

    /**
     * Gets the value of the airTptAudPsxIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAirTptAudPsxIr() {
        return airTptAudPsxIr;
    }

    /**
     * Sets the value of the airTptAudPsxIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAirTptAudPsxIr(Boolean value) {
        this.airTptAudPsxIr = value;
    }

    /**
     * Gets the value of the airTptAudOcrIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAirTptAudOcrIr() {
        return airTptAudOcrIr;
    }

    /**
     * Sets the value of the airTptAudOcrIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAirTptAudOcrIr(Boolean value) {
        this.airTptAudOcrIr = value;
    }

    /**
     * Gets the value of the cgoArcOlyIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCgoArcOlyIr() {
        return cgoArcOlyIr;
    }

    /**
     * Sets the value of the cgoArcOlyIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCgoArcOlyIr(Boolean value) {
        this.cgoArcOlyIr = value;
    }

    /**
     * Gets the value of the tptMdeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTptMdeCd() {
        return tptMdeCd;
    }

    /**
     * Sets the value of the tptMdeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTptMdeCd(String value) {
        this.tptMdeCd = value;
    }

    /**
     * Gets the value of the tunResCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTunResCd() {
        return tunResCd;
    }

    /**
     * Sets the value of the tunResCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTunResCd(String value) {
        this.tunResCd = value;
    }

    /**
     * Gets the value of the datCpMthCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpMthCgyCd() {
        return datCpMthCgyCd;
    }

    /**
     * Sets the value of the datCpMthCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpMthCgyCd(String value) {
        this.datCpMthCgyCd = value;
    }

    /**
     * Gets the value of the datCpInfSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpInfSrcCd() {
        return datCpInfSrcCd;
    }

    /**
     * Sets the value of the datCpInfSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpInfSrcCd(String value) {
        this.datCpInfSrcCd = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
