//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for LdUntTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LdUntTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}CrtDt" minOccurs="0"/>
 *         &lt;element ref="{upscm}UtcTcfTmQy" minOccurs="0"/>
 *         &lt;element ref="{upscm}OrgOgzCnyCd"/>
 *         &lt;element ref="{upscm}OrgOgzNr"/>
 *         &lt;element ref="{upscm}OrgSrtTypCd"/>
 *         &lt;element ref="{upscm}DtnOgzCnyCd"/>
 *         &lt;element ref="{upscm}DtnOgzNr"/>
 *         &lt;element ref="{upscm}DtnSrtTypCd"/>
 *         &lt;element name="LdNa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LdUntNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LdUntTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrnRteNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RteNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SvcTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SrtBltNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SrtBayNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}RefDatDxnCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LdUntTyp", propOrder = {
    "crtDt",
    "utcTcfTmQy",
    "orgOgzCnyCd",
    "orgOgzNr",
    "orgSrtTypCd",
    "dtnOgzCnyCd",
    "dtnOgzNr",
    "dtnSrtTypCd",
    "ldNa",
    "ldUntNr",
    "ldUntTypCd",
    "prnRteNr",
    "rteNr",
    "svcTypCd",
    "srtBltNr",
    "srtBayNr"
})
@JsonInclude(Include.NON_NULL)
public class LdUntTyp {

    @XmlElement(name = "CrtDt", namespace = "upscm")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String crtDt;
    @XmlElement(name = "UtcTcfTmQy", namespace = "upscm")
    protected String utcTcfTmQy;
    @XmlElement(name = "OrgOgzCnyCd", namespace = "upscm", required = true)
    protected String orgOgzCnyCd;
    @XmlElement(name = "OrgOgzNr", namespace = "upscm", required = true)
    protected String orgOgzNr;
    @XmlElement(name = "OrgSrtTypCd", namespace = "upscm", required = true)
    protected String orgSrtTypCd;
    @XmlElement(name = "DtnOgzCnyCd", namespace = "upscm", required = true)
    protected String dtnOgzCnyCd;
    @XmlElement(name = "DtnOgzNr", namespace = "upscm", required = true)
    protected String dtnOgzNr;
    @XmlElement(name = "DtnSrtTypCd", namespace = "upscm", required = true)
    protected String dtnSrtTypCd;
    @XmlElement(name = "LdNa")
    protected String ldNa;
    @XmlElement(name = "LdUntNr")
    protected String ldUntNr;
    @XmlElement(name = "LdUntTypCd")
    protected String ldUntTypCd;
    @XmlElement(name = "PrnRteNr")
    protected String prnRteNr;
    @XmlElement(name = "RteNr")
    protected String rteNr;
    @XmlElement(name = "SvcTypCd")
    protected String svcTypCd;
    @XmlElement(name = "SrtBltNr")
    protected String srtBltNr;
    @XmlElement(name = "SrtBayNr")
    protected String srtBayNr;
    @XmlAttribute(name = "RefDatDxnCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String refDatDxnCd;

    /**
     * Gets the value of the crtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getCrtDt() {
        return crtDt;
    }

    /**
     * Sets the value of the crtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCrtDt(String value) {
        this.crtDt = value;
    }

    /**
     * Gets the value of the utcTcfTmQy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtcTcfTmQy() {
        return utcTcfTmQy;
    }

    /**
     * Sets the value of the utcTcfTmQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtcTcfTmQy(String value) {
        this.utcTcfTmQy = value;
    }

    /**
     * Gets the value of the orgOgzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgOgzCnyCd() {
        return orgOgzCnyCd;
    }

    /**
     * Sets the value of the orgOgzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgOgzCnyCd(String value) {
        this.orgOgzCnyCd = value;
    }

    /**
     * Gets the value of the orgOgzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgOgzNr() {
        return orgOgzNr;
    }

    /**
     * Sets the value of the orgOgzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgOgzNr(String value) {
        this.orgOgzNr = value;
    }

    /**
     * Gets the value of the orgSrtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgSrtTypCd() {
        return orgSrtTypCd;
    }

    /**
     * Sets the value of the orgSrtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgSrtTypCd(String value) {
        this.orgSrtTypCd = value;
    }

    /**
     * Gets the value of the dtnOgzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtnOgzCnyCd() {
        return dtnOgzCnyCd;
    }

    /**
     * Sets the value of the dtnOgzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtnOgzCnyCd(String value) {
        this.dtnOgzCnyCd = value;
    }

    /**
     * Gets the value of the dtnOgzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtnOgzNr() {
        return dtnOgzNr;
    }

    /**
     * Sets the value of the dtnOgzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtnOgzNr(String value) {
        this.dtnOgzNr = value;
    }

    /**
     * Gets the value of the dtnSrtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtnSrtTypCd() {
        return dtnSrtTypCd;
    }

    /**
     * Sets the value of the dtnSrtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtnSrtTypCd(String value) {
        this.dtnSrtTypCd = value;
    }

    /**
     * Gets the value of the ldNa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdNa() {
        return ldNa;
    }

    /**
     * Sets the value of the ldNa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdNa(String value) {
        this.ldNa = value;
    }

    /**
     * Gets the value of the ldUntNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdUntNr() {
        return ldUntNr;
    }

    /**
     * Sets the value of the ldUntNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdUntNr(String value) {
        this.ldUntNr = value;
    }

    /**
     * Gets the value of the ldUntTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdUntTypCd() {
        return ldUntTypCd;
    }

    /**
     * Sets the value of the ldUntTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdUntTypCd(String value) {
        this.ldUntTypCd = value;
    }

    /**
     * Gets the value of the prnRteNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrnRteNr() {
        return prnRteNr;
    }

    /**
     * Sets the value of the prnRteNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrnRteNr(String value) {
        this.prnRteNr = value;
    }

    /**
     * Gets the value of the rteNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRteNr() {
        return rteNr;
    }

    /**
     * Sets the value of the rteNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRteNr(String value) {
        this.rteNr = value;
    }

    /**
     * Gets the value of the svcTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcTypCd() {
        return svcTypCd;
    }

    /**
     * Sets the value of the svcTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcTypCd(String value) {
        this.svcTypCd = value;
    }

    /**
     * Gets the value of the srtBltNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtBltNr() {
        return srtBltNr;
    }

    /**
     * Sets the value of the srtBltNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtBltNr(String value) {
        this.srtBltNr = value;
    }

    /**
     * Gets the value of the srtBayNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtBayNr() {
        return srtBayNr;
    }

    /**
     * Sets the value of the srtBayNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtBayNr(String value) {
        this.srtBayNr = value;
    }

    /**
     * Gets the value of the refDatDxnCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDatDxnCd() {
        return refDatDxnCd;
    }

    /**
     * Sets the value of the refDatDxnCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDatDxnCd(String value) {
        this.refDatDxnCd = value;
    }

}
