//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}AcyDt"/>
 *         &lt;element ref="{upscm}AcyTm" minOccurs="0"/>
 *         &lt;element ref="{upscm}UtcTcfTmQy" minOccurs="0"/>
 *         &lt;element ref="{upscm}OgzCnyCd"/>
 *         &lt;element ref="{upscm}OgzNr"/>
 *         &lt;element ref="{upscm}SrtTypCd"/>
 *         &lt;element ref="{upscm}Dcv" minOccurs="0"/>
 *         &lt;element ref="{upscm}Rpt" minOccurs="0"/>
 *         &lt;element ref="{upscm}Rpy" minOccurs="0"/>
 *         &lt;element name="UldAcyDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="UldAcyTm" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="UldAcyUtcTcfTmQy" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element ref="{upscm}AcyTypCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}StsCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}SraCd" minOccurs="0"/>
 *         &lt;element name="UsrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}PkgLocRlCd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}DatCpMthCgyCd"/>
 *       &lt;attribute ref="{upscm}DatCpInfSrcCd"/>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acyDt",
    "acyTm",
    "utcTcfTmQy",
    "ogzCnyCd",
    "ogzNr",
    "srtTypCd",
    "dcv",
    "rpt",
    "rpy",
    "uldAcyDt",
    "uldAcyTm",
    "uldAcyUtcTcfTmQy",
    "acyTypCd",
    "stsCd",
    "sraCd",
    "usrNr",
    "pkgLocRlCd"
})
@XmlRootElement(name = "LdUntAcy")
@JsonInclude(Include.NON_NULL)
public class LdUntAcy {

    @XmlElement(name = "AcyDt", namespace = "upscm", required = true)
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String acyDt;
    @XmlElement(name = "AcyTm", namespace = "upscm")
    @XmlSchemaType(name = "time")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="HH:mm:ss")
    protected String acyTm;
    @XmlElement(name = "UtcTcfTmQy", namespace = "upscm")
    protected String utcTcfTmQy;
    @XmlElement(name = "OgzCnyCd", namespace = "upscm", required = true)
    protected String ogzCnyCd;
    @XmlElement(name = "OgzNr", namespace = "upscm", required = true)
    protected String ogzNr;
    @XmlElement(name = "SrtTypCd", namespace = "upscm", required = true)
    protected String srtTypCd;
    @XmlElement(name = "Dcv", namespace = "upscm")
    protected OgzDtTmTyp dcv;
    @XmlElement(name = "Rpt", namespace = "upscm")
    protected OgzDtTmTyp rpt;
    @XmlElement(name = "Rpy", namespace = "upscm")
    protected OgzDtTmTyp rpy;
    @XmlElement(name = "UldAcyDt")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String uldAcyDt;
    @XmlElement(name = "UldAcyTm")
    @XmlSchemaType(name = "time")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="HH:mm:ss")
    protected String uldAcyTm;
    @XmlElement(name = "UldAcyUtcTcfTmQy")
    protected BigDecimal uldAcyUtcTcfTmQy;
    @XmlElement(name = "AcyTypCd", namespace = "upscm")
    protected String acyTypCd;
    @XmlElement(name = "StsCd", namespace = "upscm")
    protected String stsCd;
    @XmlElement(name = "SraCd", namespace = "upscm")
    protected String sraCd;
    @XmlElement(name = "UsrNr")
    protected String usrNr;
    @XmlElement(name = "PkgLocRlCd", namespace = "upscm")
    protected String pkgLocRlCd;
    @XmlAttribute(name = "DatCpMthCgyCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpMthCgyCd;
    @XmlAttribute(name = "DatCpInfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpInfSrcCd;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the acyDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAcyDt() {
        return acyDt;
    }

    /**
     * Sets the value of the acyDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcyDt(String value) {
        this.acyDt = value;
    }

    /**
     * Gets the value of the acyTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAcyTm() {
        return acyTm;
    }

    /**
     * Sets the value of the acyTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcyTm(String value) {
        this.acyTm = value;
    }

    /**
     * Gets the value of the utcTcfTmQy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtcTcfTmQy() {
        return utcTcfTmQy;
    }

    /**
     * Sets the value of the utcTcfTmQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtcTcfTmQy(String value) {
        this.utcTcfTmQy = value;
    }

    /**
     * Gets the value of the ogzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzCnyCd() {
        return ogzCnyCd;
    }

    /**
     * Sets the value of the ogzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzCnyCd(String value) {
        this.ogzCnyCd = value;
    }

    /**
     * Gets the value of the ogzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzNr() {
        return ogzNr;
    }

    /**
     * Sets the value of the ogzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzNr(String value) {
        this.ogzNr = value;
    }

    /**
     * Gets the value of the srtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypCd() {
        return srtTypCd;
    }

    /**
     * Sets the value of the srtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypCd(String value) {
        this.srtTypCd = value;
    }

    /**
     * Gets the value of the dcv property.
     * 
     * @return
     *     possible object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public OgzDtTmTyp getDcv() {
        return dcv;
    }

    /**
     * Sets the value of the dcv property.
     * 
     * @param value
     *     allowed object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public void setDcv(OgzDtTmTyp value) {
        this.dcv = value;
    }

    /**
     * Gets the value of the rpt property.
     * 
     * @return
     *     possible object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public OgzDtTmTyp getRpt() {
        return rpt;
    }

    /**
     * Sets the value of the rpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public void setRpt(OgzDtTmTyp value) {
        this.rpt = value;
    }

    /**
     * Gets the value of the rpy property.
     * 
     * @return
     *     possible object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public OgzDtTmTyp getRpy() {
        return rpy;
    }

    /**
     * Sets the value of the rpy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public void setRpy(OgzDtTmTyp value) {
        this.rpy = value;
    }

    /**
     * Gets the value of the uldAcyDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getUldAcyDt() {
        return uldAcyDt;
    }

    /**
     * Sets the value of the uldAcyDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUldAcyDt(String value) {
        this.uldAcyDt = value;
    }

    /**
     * Gets the value of the uldAcyTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getUldAcyTm() {
        return uldAcyTm;
    }

    /**
     * Sets the value of the uldAcyTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUldAcyTm(String value) {
        this.uldAcyTm = value;
    }

    /**
     * Gets the value of the uldAcyUtcTcfTmQy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUldAcyUtcTcfTmQy() {
        return uldAcyUtcTcfTmQy;
    }

    /**
     * Sets the value of the uldAcyUtcTcfTmQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUldAcyUtcTcfTmQy(BigDecimal value) {
        this.uldAcyUtcTcfTmQy = value;
    }

    /**
     * Gets the value of the acyTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcyTypCd() {
        return acyTypCd;
    }

    /**
     * Sets the value of the acyTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcyTypCd(String value) {
        this.acyTypCd = value;
    }

    /**
     * Gets the value of the stsCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * Sets the value of the stsCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStsCd(String value) {
        this.stsCd = value;
    }

    /**
     * Gets the value of the sraCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSraCd() {
        return sraCd;
    }

    /**
     * Sets the value of the sraCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSraCd(String value) {
        this.sraCd = value;
    }

    /**
     * Gets the value of the usrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrNr() {
        return usrNr;
    }

    /**
     * Sets the value of the usrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrNr(String value) {
        this.usrNr = value;
    }

    /**
     * Gets the value of the pkgLocRlCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkgLocRlCd() {
        return pkgLocRlCd;
    }

    /**
     * Sets the value of the pkgLocRlCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkgLocRlCd(String value) {
        this.pkgLocRlCd = value;
    }

    /**
     * Gets the value of the datCpMthCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpMthCgyCd() {
        return datCpMthCgyCd;
    }

    /**
     * Sets the value of the datCpMthCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpMthCgyCd(String value) {
        this.datCpMthCgyCd = value;
    }

    /**
     * Gets the value of the datCpInfSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpInfSrcCd() {
        return datCpInfSrcCd;
    }

    /**
     * Sets the value of the datCpInfSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpInfSrcCd(String value) {
        this.datCpInfSrcCd = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
