//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for MnyTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MnyTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AcpPmtCgyCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CcyAlpCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PymCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MnyTyp", propOrder = {
    "a",
    "acpPmtCgyCd",
    "codIr",
    "ccyAlpCd",
    "pymCd"
})
@JsonInclude(Include.NON_NULL)
public class MnyTyp {

    @XmlElement(name = "A")
    protected BigDecimal a;
    @XmlElement(name = "AcpPmtCgyCd")
    protected String acpPmtCgyCd;
    @XmlElement(name = "CodIr")
    protected Boolean codIr;
    @XmlElement(name = "CcyAlpCd")
    protected String ccyAlpCd;
    @XmlElement(name = "PymCd")
    protected String pymCd;

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setA(BigDecimal value) {
        this.a = value;
    }

    /**
     * Gets the value of the acpPmtCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcpPmtCgyCd() {
        return acpPmtCgyCd;
    }

    /**
     * Sets the value of the acpPmtCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcpPmtCgyCd(String value) {
        this.acpPmtCgyCd = value;
    }

    /**
     * Gets the value of the codIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCodIr() {
        return codIr;
    }

    /**
     * Sets the value of the codIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCodIr(Boolean value) {
        this.codIr = value;
    }

    /**
     * Gets the value of the ccyAlpCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcyAlpCd() {
        return ccyAlpCd;
    }

    /**
     * Sets the value of the ccyAlpCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcyAlpCd(String value) {
        this.ccyAlpCd = value;
    }

    /**
     * Gets the value of the pymCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPymCd() {
        return pymCd;
    }

    /**
     * Sets the value of the pymCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPymCd(String value) {
        this.pymCd = value;
    }

}
