//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}OrgOgzCnyCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}OrgOgzNr" minOccurs="0"/>
 *         &lt;element ref="{upscm}DtnOgzCnyCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}DtnOgzNr" minOccurs="0"/>
 *         &lt;element name="MvmDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="MnmNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MvmNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orgOgzCnyCd",
    "orgOgzNr",
    "dtnOgzCnyCd",
    "dtnOgzNr",
    "mvmDt",
    "mnmNr",
    "mvmNr"
})
@XmlRootElement(name = "Mvm")
@JsonInclude(Include.NON_NULL)
public class Mvm {

    @XmlElement(name = "OrgOgzCnyCd", namespace = "upscm")
    protected String orgOgzCnyCd;
    @XmlElement(name = "OrgOgzNr", namespace = "upscm")
    protected String orgOgzNr;
    @XmlElement(name = "DtnOgzCnyCd", namespace = "upscm")
    protected String dtnOgzCnyCd;
    @XmlElement(name = "DtnOgzNr", namespace = "upscm")
    protected String dtnOgzNr;
    @XmlElement(name = "MvmDt")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String mvmDt;
    @XmlElement(name = "MnmNr")
    protected String mnmNr;
    @XmlElement(name = "MvmNr")
    protected String mvmNr;

    /**
     * Gets the value of the orgOgzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgOgzCnyCd() {
        return orgOgzCnyCd;
    }

    /**
     * Sets the value of the orgOgzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgOgzCnyCd(String value) {
        this.orgOgzCnyCd = value;
    }

    /**
     * Gets the value of the orgOgzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgOgzNr() {
        return orgOgzNr;
    }

    /**
     * Sets the value of the orgOgzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgOgzNr(String value) {
        this.orgOgzNr = value;
    }

    /**
     * Gets the value of the dtnOgzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtnOgzCnyCd() {
        return dtnOgzCnyCd;
    }

    /**
     * Sets the value of the dtnOgzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtnOgzCnyCd(String value) {
        this.dtnOgzCnyCd = value;
    }

    /**
     * Gets the value of the dtnOgzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtnOgzNr() {
        return dtnOgzNr;
    }

    /**
     * Sets the value of the dtnOgzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtnOgzNr(String value) {
        this.dtnOgzNr = value;
    }

    /**
     * Gets the value of the mvmDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getMvmDt() {
        return mvmDt;
    }

    /**
     * Sets the value of the mvmDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMvmDt(String value) {
        this.mvmDt = value;
    }

    /**
     * Gets the value of the mnmNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMnmNr() {
        return mnmNr;
    }

    /**
     * Sets the value of the mnmNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMnmNr(String value) {
        this.mnmNr = value;
    }

    /**
     * Gets the value of the mvmNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMvmNr() {
        return mvmNr;
    }

    /**
     * Sets the value of the mvmNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMvmNr(String value) {
        this.mvmNr = value;
    }

}
