//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ups.heat.ingestion.gio.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SraCd_QNAME = new QName("upscm", "SraCd");
    private final static QName _FacCnyCd_QNAME = new QName("upscm", "FacCnyCd");
    private final static QName _MsuCd_QNAME = new QName("upscm", "MsuCd");
    private final static QName _SrtDt_QNAME = new QName("upscm", "SrtDt");
    private final static QName _CnySdvCd_QNAME = new QName("upscm", "CnySdvCd");
    private final static QName _PkgLocRlCd_QNAME = new QName("upscm", "PkgLocRlCd");
    private final static QName _DtnOgzNr_QNAME = new QName("upscm", "DtnOgzNr");
    private final static QName _Qy_QNAME = new QName("upscm", "Qy");
    private final static QName _Rpt_QNAME = new QName("upscm", "Rpt");
    private final static QName _MsuDscTe_QNAME = new QName("upscm", "MsuDscTe");
    private final static QName _OrgOgzCnyCd_QNAME = new QName("upscm", "OrgOgzCnyCd");
    private final static QName _AcyTm_QNAME = new QName("upscm", "AcyTm");
    private final static QName _OutLdUnt_QNAME = new QName("upscm", "OutLdUnt");
    private final static QName _CrtDt_QNAME = new QName("upscm", "CrtDt");
    private final static QName _LdUnt_QNAME = new QName("upscm", "LdUnt");
    private final static QName _AcyTypCd_QNAME = new QName("upscm", "AcyTypCd");
    private final static QName _StsCd_QNAME = new QName("upscm", "StsCd");
    private final static QName _FacMnmTe_QNAME = new QName("upscm", "FacMnmTe");
    private final static QName _Rpy_QNAME = new QName("upscm", "Rpy");
    private final static QName _IptCod_QNAME = new QName("upscm", "IptCod");
    private final static QName _OrgSrtTypCd_QNAME = new QName("upscm", "OrgSrtTypCd");
    private final static QName _Cod_QNAME = new QName("upscm", "Cod");
    private final static QName _AcyDt_QNAME = new QName("upscm", "AcyDt");
    private final static QName _SrtTypCd_QNAME = new QName("upscm", "SrtTypCd");
    private final static QName _OgzNr_QNAME = new QName("upscm", "OgzNr");
    private final static QName _UtcTcfTmQy_QNAME = new QName("upscm", "UtcTcfTmQy");
    private final static QName _CnyCd_QNAME = new QName("upscm", "CnyCd");
    private final static QName _DtnOgzCnyCd_QNAME = new QName("upscm", "DtnOgzCnyCd");
    private final static QName _D2RCod_QNAME = new QName("upscm", "D2rCod");
    private final static QName _Dcv_QNAME = new QName("upscm", "Dcv");
    private final static QName _LstLegLdUnt_QNAME = new QName("upscm", "LstLegLdUnt");
    private final static QName _DtnSrtTypCd_QNAME = new QName("upscm", "DtnSrtTypCd");
    private final static QName _SrtTs_QNAME = new QName("upscm", "SrtTs");
    private final static QName _OrgOgzNr_QNAME = new QName("upscm", "OrgOgzNr");
    private final static QName _MsuMnmTe_QNAME = new QName("upscm", "MsuMnmTe");
    private final static QName _FacLocNr_QNAME = new QName("upscm", "FacLocNr");
    private final static QName _OgzCnyCd_QNAME = new QName("upscm", "OgzCnyCd");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ups.heat.ingestion.gio.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DmnTyp }
     * 
     */
    public DmnTyp createDmnTyp() {
        return new DmnTyp();
    }

    /**
     * Create an instance of {@link Shu.CurPrcFacOgz }
     * 
     */
    public Shu.CurPrcFacOgz createShuCurPrcFacOgz() {
        return new Shu.CurPrcFacOgz();
    }

    /**
     * Create an instance of {@link PkgSt }
     * 
     */
    public PkgSt createPkgSt() {
        return new PkgSt();
    }

    /**
     * Create an instance of {@link Shu.PkgTckNr }
     * 
     */
    public Shu.PkgTckNr createShuPkgTckNr() {
        return new Shu.PkgTckNr();
    }

    /**
     * Create an instance of {@link DelAcy }
     * 
     */
    public DelAcy createDelAcy() {
        return new DelAcy();
    }

    /**
     * Create an instance of {@link WgtTyp }
     * 
     */
    public WgtTyp createWgtTyp() {
        return new WgtTyp();
    }

    /**
     * Create an instance of {@link DelDtTmTyp.RddTm }
     * 
     */
    public DelDtTmTyp.RddTm createDelDtTmTypRddTm() {
        return new DelDtTmTyp.RddTm();
    }

    /**
     * Create an instance of {@link LdUntTyp }
     * 
     */
    public LdUntTyp createLdUntTyp() {
        return new LdUntTyp();
    }

    /**
     * Create an instance of {@link Shu.Svc }
     * 
     */
    public Shu.Svc createShuSvc() {
        return new Shu.Svc();
    }

    /**
     * Create an instance of {@link Smt }
     * 
     */
    public Smt createSmt() {
        return new Smt();
    }

    /**
     * Create an instance of {@link Shu.Fcs }
     * 
     */
    public Shu.Fcs createShuFcs() {
        return new Shu.Fcs();
    }

    /**
     * Create an instance of {@link MsgHdr }
     * 
     */
    public MsgHdr createMsgHdr() {
        return new MsgHdr();
    }

    /**
     * Create an instance of {@link DelDtTmTyp.RcdTm }
     * 
     */
    public DelDtTmTyp.RcdTm createDelDtTmTypRcdTm() {
        return new DelDtTmTyp.RcdTm();
    }

    /**
     * Create an instance of {@link AcsPntTyp }
     * 
     */
    public AcsPntTyp createAcsPntTyp() {
        return new AcsPntTyp();
    }

    /**
     * Create an instance of {@link MnyTyp }
     * 
     */
    public MnyTyp createMnyTyp() {
        return new MnyTyp();
    }

    /**
     * Create an instance of {@link Shu.Lop }
     * 
     */
    public Shu.Lop createShuLop() {
        return new Shu.Lop();
    }

    /**
     * Create an instance of {@link Shu.Flo.PriOgz.AltOgz }
     * 
     */
    public Shu.Flo.PriOgz.AltOgz createShuFloPriOgzAltOgz() {
        return new Shu.Flo.PriOgz.AltOgz();
    }

    /**
     * Create an instance of {@link Shu }
     * 
     */
    public Shu createShu() {
        return new Shu();
    }

    /**
     * Create an instance of {@link Ctm }
     * 
     */
    public Ctm createCtm() {
        return new Ctm();
    }

    /**
     * Create an instance of {@link Shu.Flo.PriOgz }
     * 
     */
    public Shu.Flo.PriOgz createShuFloPriOgz() {
        return new Shu.Flo.PriOgz();
    }

    /**
     * Create an instance of {@link AdTyp }
     * 
     */
    public AdTyp createAdTyp() {
        return new AdTyp();
    }

    /**
     * Create an instance of {@link BpyTyp }
     * 
     */
    public BpyTyp createBpyTyp() {
        return new BpyTyp();
    }

    /**
     * Create an instance of {@link DelDtTmTyp.RddDt }
     * 
     */
    public DelDtTmTyp.RddDt createDelDtTmTypRddDt() {
        return new DelDtTmTyp.RddDt();
    }

    /**
     * Create an instance of {@link XcpAcy }
     * 
     */
    public XcpAcy createXcpAcy() {
        return new XcpAcy();
    }

    /**
     * Create an instance of {@link LdUntAcy }
     * 
     */
    public LdUntAcy createLdUntAcy() {
        return new LdUntAcy();
    }

    /**
     * Create an instance of {@link Shu.CnsAd }
     * 
     */
    public Shu.CnsAd createShuCnsAd() {
        return new Shu.CnsAd();
    }

    /**
     * Create an instance of {@link Shu.ShuElg }
     * 
     */
    public Shu.ShuElg createShuShuElg() {
        return new Shu.ShuElg();
    }

    /**
     * Create an instance of {@link RglCmy }
     * 
     */
    public RglCmy createRglCmy() {
        return new RglCmy();
    }

    /**
     * Create an instance of {@link DelDtTmTyp.RcdDt }
     * 
     */
    public DelDtTmTyp.RcdDt createDelDtTmTypRcdDt() {
        return new DelDtTmTyp.RcdDt();
    }

    /**
     * Create an instance of {@link PesTyp }
     * 
     */
    public PesTyp createPesTyp() {
        return new PesTyp();
    }

    /**
     * Create an instance of {@link FcsSrtAcy }
     * 
     */
    public FcsSrtAcy createFcsSrtAcy() {
        return new FcsSrtAcy();
    }

    /**
     * Create an instance of {@link Shu.Flo }
     * 
     */
    public Shu.Flo createShuFlo() {
        return new Shu.Flo();
    }

    /**
     * Create an instance of {@link SecUnt }
     * 
     */
    public SecUnt createSecUnt() {
        return new SecUnt();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link OgzTyp }
     * 
     */
    public OgzTyp createOgzTyp() {
        return new OgzTyp();
    }

    /**
     * Create an instance of {@link InlPkgUdtAcy }
     * 
     */
    public InlPkgUdtAcy createInlPkgUdtAcy() {
        return new InlPkgUdtAcy();
    }

    /**
     * Create an instance of {@link SnAcy }
     * 
     */
    public SnAcy createSnAcy() {
        return new SnAcy();
    }

    /**
     * Create an instance of {@link DelDtTmTyp }
     * 
     */
    public DelDtTmTyp createDelDtTmTyp() {
        return new DelDtTmTyp();
    }

    /**
     * Create an instance of {@link Mvm }
     * 
     */
    public Mvm createMvm() {
        return new Mvm();
    }

    /**
     * Create an instance of {@link SycDelAcy }
     * 
     */
    public SycDelAcy createSycDelAcy() {
        return new SycDelAcy();
    }

    /**
     * Create an instance of {@link HzmAudAcy }
     * 
     */
    public HzmAudAcy createHzmAudAcy() {
        return new HzmAudAcy();
    }

    /**
     * Create an instance of {@link OgzDtTmTyp }
     * 
     */
    public OgzDtTmTyp createOgzDtTmTyp() {
        return new OgzDtTmTyp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "SraCd")
    public JAXBElement<String> createSraCd(String value) {
        return new JAXBElement<String>(_SraCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "FacCnyCd")
    public JAXBElement<String> createFacCnyCd(String value) {
        return new JAXBElement<String>(_FacCnyCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "MsuCd")
    public JAXBElement<String> createMsuCd(String value) {
        return new JAXBElement<String>(_MsuCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "SrtDt")
    public JAXBElement<XMLGregorianCalendar> createSrtDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SrtDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "CnySdvCd")
    public JAXBElement<String> createCnySdvCd(String value) {
        return new JAXBElement<String>(_CnySdvCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "PkgLocRlCd")
    public JAXBElement<String> createPkgLocRlCd(String value) {
        return new JAXBElement<String>(_PkgLocRlCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "DtnOgzNr")
    public JAXBElement<String> createDtnOgzNr(String value) {
        return new JAXBElement<String>(_DtnOgzNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "Qy")
    public JAXBElement<BigDecimal> createQy(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Qy_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OgzDtTmTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "Rpt")
    public JAXBElement<OgzDtTmTyp> createRpt(OgzDtTmTyp value) {
        return new JAXBElement<OgzDtTmTyp>(_Rpt_QNAME, OgzDtTmTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "MsuDscTe")
    public JAXBElement<String> createMsuDscTe(String value) {
        return new JAXBElement<String>(_MsuDscTe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "OrgOgzCnyCd")
    public JAXBElement<String> createOrgOgzCnyCd(String value) {
        return new JAXBElement<String>(_OrgOgzCnyCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "AcyTm")
    public JAXBElement<XMLGregorianCalendar> createAcyTm(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AcyTm_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdUntTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "OutLdUnt")
    public JAXBElement<LdUntTyp> createOutLdUnt(LdUntTyp value) {
        return new JAXBElement<LdUntTyp>(_OutLdUnt_QNAME, LdUntTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "CrtDt")
    public JAXBElement<XMLGregorianCalendar> createCrtDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CrtDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdUntTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "LdUnt")
    public JAXBElement<LdUntTyp> createLdUnt(LdUntTyp value) {
        return new JAXBElement<LdUntTyp>(_LdUnt_QNAME, LdUntTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "AcyTypCd")
    public JAXBElement<String> createAcyTypCd(String value) {
        return new JAXBElement<String>(_AcyTypCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "StsCd")
    public JAXBElement<String> createStsCd(String value) {
        return new JAXBElement<String>(_StsCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "FacMnmTe")
    public JAXBElement<String> createFacMnmTe(String value) {
        return new JAXBElement<String>(_FacMnmTe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OgzDtTmTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "Rpy")
    public JAXBElement<OgzDtTmTyp> createRpy(OgzDtTmTyp value) {
        return new JAXBElement<OgzDtTmTyp>(_Rpy_QNAME, OgzDtTmTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MnyTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "IptCod")
    public JAXBElement<MnyTyp> createIptCod(MnyTyp value) {
        return new JAXBElement<MnyTyp>(_IptCod_QNAME, MnyTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "OrgSrtTypCd")
    public JAXBElement<String> createOrgSrtTypCd(String value) {
        return new JAXBElement<String>(_OrgSrtTypCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MnyTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "Cod")
    public JAXBElement<MnyTyp> createCod(MnyTyp value) {
        return new JAXBElement<MnyTyp>(_Cod_QNAME, MnyTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "AcyDt")
    public JAXBElement<XMLGregorianCalendar> createAcyDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AcyDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "SrtTypCd")
    public JAXBElement<String> createSrtTypCd(String value) {
        return new JAXBElement<String>(_SrtTypCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "OgzNr")
    public JAXBElement<String> createOgzNr(String value) {
        return new JAXBElement<String>(_OgzNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "UtcTcfTmQy")
    public JAXBElement<String> createUtcTcfTmQy(String value) {
        return new JAXBElement<String>(_UtcTcfTmQy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "CnyCd")
    public JAXBElement<String> createCnyCd(String value) {
        return new JAXBElement<String>(_CnyCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "DtnOgzCnyCd")
    public JAXBElement<String> createDtnOgzCnyCd(String value) {
        return new JAXBElement<String>(_DtnOgzCnyCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MnyTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "D2rCod")
    public JAXBElement<MnyTyp> createD2RCod(MnyTyp value) {
        return new JAXBElement<MnyTyp>(_D2RCod_QNAME, MnyTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OgzDtTmTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "Dcv")
    public JAXBElement<OgzDtTmTyp> createDcv(OgzDtTmTyp value) {
        return new JAXBElement<OgzDtTmTyp>(_Dcv_QNAME, OgzDtTmTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdUntTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "LstLegLdUnt")
    public JAXBElement<LdUntTyp> createLstLegLdUnt(LdUntTyp value) {
        return new JAXBElement<LdUntTyp>(_LstLegLdUnt_QNAME, LdUntTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "DtnSrtTypCd")
    public JAXBElement<String> createDtnSrtTypCd(String value) {
        return new JAXBElement<String>(_DtnSrtTypCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "SrtTs")
    public JAXBElement<XMLGregorianCalendar> createSrtTs(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SrtTs_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "OrgOgzNr")
    public JAXBElement<String> createOrgOgzNr(String value) {
        return new JAXBElement<String>(_OrgOgzNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "MsuMnmTe")
    public JAXBElement<String> createMsuMnmTe(String value) {
        return new JAXBElement<String>(_MsuMnmTe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "FacLocNr")
    public JAXBElement<String> createFacLocNr(String value) {
        return new JAXBElement<String>(_FacLocNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "upscm", name = "OgzCnyCd")
    public JAXBElement<String> createOgzCnyCd(String value) {
        return new JAXBElement<String>(_OgzCnyCd_QNAME, String.class, null, value);
    }

}
