//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for OgzDtTmTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OgzDtTmTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Tm" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element ref="{upscm}UtcTcfTmQy" minOccurs="0"/>
 *         &lt;element ref="{upscm}OgzCnyCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}OgzNr" minOccurs="0"/>
 *         &lt;element ref="{upscm}SrtTypCd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OgzDtTmTyp", propOrder = {
    "dt",
    "tm",
    "utcTcfTmQy",
    "ogzCnyCd",
    "ogzNr",
    "srtTypCd"
})
@JsonInclude(Include.NON_NULL)
public class OgzDtTmTyp {

    @XmlElement(name = "Dt")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String dt;
    @XmlElement(name = "Tm")
    @XmlSchemaType(name = "time")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="HH:mm:ss")
    protected String tm;
    @XmlElement(name = "UtcTcfTmQy", namespace = "upscm")
    protected String utcTcfTmQy;
    @XmlElement(name = "OgzCnyCd", namespace = "upscm")
    protected String ogzCnyCd;
    @XmlElement(name = "OgzNr", namespace = "upscm")
    protected String ogzNr;
    @XmlElement(name = "SrtTypCd", namespace = "upscm")
    protected String srtTypCd;

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDt(String value) {
        this.dt = value;
    }

    /**
     * Gets the value of the tm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTm() {
        return tm;
    }

    /**
     * Sets the value of the tm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTm(String value) {
        this.tm = value;
    }

    /**
     * Gets the value of the utcTcfTmQy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtcTcfTmQy() {
        return utcTcfTmQy;
    }

    /**
     * Sets the value of the utcTcfTmQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtcTcfTmQy(String value) {
        this.utcTcfTmQy = value;
    }

    /**
     * Gets the value of the ogzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzCnyCd() {
        return ogzCnyCd;
    }

    /**
     * Sets the value of the ogzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzCnyCd(String value) {
        this.ogzCnyCd = value;
    }

    /**
     * Gets the value of the ogzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzNr() {
        return ogzNr;
    }

    /**
     * Sets the value of the ogzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzNr(String value) {
        this.ogzNr = value;
    }

    /**
     * Gets the value of the srtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypCd() {
        return srtTypCd;
    }

    /**
     * Sets the value of the srtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypCd(String value) {
        this.srtTypCd = value;
    }

}
