//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for OgzTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OgzTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}CnyCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}OgzNr" minOccurs="0"/>
 *         &lt;element name="FacCnyCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}FacLocNr" minOccurs="0"/>
 *         &lt;element ref="{upscm}FacMnmTe" minOccurs="0"/>
 *         &lt;element name="FacDyrCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}SrtTypCd" minOccurs="0"/>
 *         &lt;element name="SrtTypMnmTe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SrtTypOcrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}SrtDt" minOccurs="0"/>
 *         &lt;element ref="{upscm}SrtTs" minOccurs="0"/>
 *         &lt;element name="InBdgLocNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SvcPntDelLocNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShuLocRlCgyCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LdCrtDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="LdSvcTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UsrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}DatSrcMnmTe"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OgzTyp", propOrder = {
    "cnyCd",
    "ogzNr",
    "facCnyCd",
    "facLocNr",
    "facMnmTe",
    "facDyrCd",
    "srtTypCd",
    "srtTypMnmTe",
    "srtTypOcrNr",
    "srtDt",
    "srtTs",
    "inBdgLocNr",
    "svcPntDelLocNr",
    "shuLocRlCgyCd",
    "ldCrtDt",
    "ldSvcTypCd",
    "usrNr"
})
@XmlSeeAlso({
    com.rajantech.camel.jaxb.model.Shu.CurPrcFacOgz.class,
    com.rajantech.camel.jaxb.model.Shu.Flo.PriOgz.AltOgz.class,
    com.rajantech.camel.jaxb.model.Shu.Flo.PriOgz.class
})
@JsonInclude(Include.NON_NULL)
public class OgzTyp {

    @XmlElement(name = "CnyCd", namespace = "upscm")
    protected String cnyCd;
    @XmlElement(name = "OgzNr", namespace = "upscm")
    protected String ogzNr;
    @XmlElement(name = "FacCnyCd")
    protected String facCnyCd;
    @XmlElement(name = "FacLocNr", namespace = "upscm")
    protected String facLocNr;
    @XmlElement(name = "FacMnmTe", namespace = "upscm")
    protected String facMnmTe;
    @XmlElement(name = "FacDyrCd")
    protected String facDyrCd;
    @XmlElement(name = "SrtTypCd", namespace = "upscm")
    protected String srtTypCd;
    @XmlElement(name = "SrtTypMnmTe")
    protected String srtTypMnmTe;
    @XmlElement(name = "SrtTypOcrNr")
    protected String srtTypOcrNr;
    @XmlElement(name = "SrtDt", namespace = "upscm")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String srtDt;
    @XmlElement(name = "SrtTs", namespace = "upscm")
    @XmlSchemaType(name = "dateTime")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss")
    protected String srtTs;
    @XmlElement(name = "InBdgLocNr")
    protected String inBdgLocNr;
    @XmlElement(name = "SvcPntDelLocNr")
    protected String svcPntDelLocNr;
    @XmlElement(name = "ShuLocRlCgyCd")
    protected String shuLocRlCgyCd;
    @XmlElement(name = "LdCrtDt")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String ldCrtDt;
    @XmlElement(name = "LdSvcTypCd")
    protected String ldSvcTypCd;
    @XmlElement(name = "UsrNr")
    protected String usrNr;
    @XmlAttribute(name = "DatSrcMnmTe", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datSrcMnmTe;

    /**
     * Gets the value of the cnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnyCd() {
        return cnyCd;
    }

    /**
     * Sets the value of the cnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnyCd(String value) {
        this.cnyCd = value;
    }

    /**
     * Gets the value of the ogzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzNr() {
        return ogzNr;
    }

    /**
     * Sets the value of the ogzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzNr(String value) {
        this.ogzNr = value;
    }

    /**
     * Gets the value of the facCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacCnyCd() {
        return facCnyCd;
    }

    /**
     * Sets the value of the facCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacCnyCd(String value) {
        this.facCnyCd = value;
    }

    /**
     * Gets the value of the facLocNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacLocNr() {
        return facLocNr;
    }

    /**
     * Sets the value of the facLocNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacLocNr(String value) {
        this.facLocNr = value;
    }

    /**
     * Gets the value of the facMnmTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacMnmTe() {
        return facMnmTe;
    }

    /**
     * Sets the value of the facMnmTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacMnmTe(String value) {
        this.facMnmTe = value;
    }

    /**
     * Gets the value of the facDyrCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacDyrCd() {
        return facDyrCd;
    }

    /**
     * Sets the value of the facDyrCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacDyrCd(String value) {
        this.facDyrCd = value;
    }

    /**
     * Gets the value of the srtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypCd() {
        return srtTypCd;
    }

    /**
     * Sets the value of the srtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypCd(String value) {
        this.srtTypCd = value;
    }

    /**
     * Gets the value of the srtTypMnmTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypMnmTe() {
        return srtTypMnmTe;
    }

    /**
     * Sets the value of the srtTypMnmTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypMnmTe(String value) {
        this.srtTypMnmTe = value;
    }

    /**
     * Gets the value of the srtTypOcrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypOcrNr() {
        return srtTypOcrNr;
    }

    /**
     * Sets the value of the srtTypOcrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypOcrNr(String value) {
        this.srtTypOcrNr = value;
    }

    /**
     * Gets the value of the srtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getSrtDt() {
        return srtDt;
    }

    /**
     * Sets the value of the srtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSrtDt(String value) {
        this.srtDt = value;
    }

    /**
     * Gets the value of the srtTs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getSrtTs() {
        return srtTs;
    }

    /**
     * Sets the value of the srtTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSrtTs(String value) {
        this.srtTs = value;
    }

    /**
     * Gets the value of the inBdgLocNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBdgLocNr() {
        return inBdgLocNr;
    }

    /**
     * Sets the value of the inBdgLocNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBdgLocNr(String value) {
        this.inBdgLocNr = value;
    }

    /**
     * Gets the value of the svcPntDelLocNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcPntDelLocNr() {
        return svcPntDelLocNr;
    }

    /**
     * Sets the value of the svcPntDelLocNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcPntDelLocNr(String value) {
        this.svcPntDelLocNr = value;
    }

    /**
     * Gets the value of the shuLocRlCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShuLocRlCgyCd() {
        return shuLocRlCgyCd;
    }

    /**
     * Sets the value of the shuLocRlCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShuLocRlCgyCd(String value) {
        this.shuLocRlCgyCd = value;
    }

    /**
     * Gets the value of the ldCrtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getLdCrtDt() {
        return ldCrtDt;
    }

    /**
     * Sets the value of the ldCrtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLdCrtDt(String value) {
        this.ldCrtDt = value;
    }

    /**
     * Gets the value of the ldSvcTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdSvcTypCd() {
        return ldSvcTypCd;
    }

    /**
     * Sets the value of the ldSvcTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdSvcTypCd(String value) {
        this.ldSvcTypCd = value;
    }

    /**
     * Gets the value of the usrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrNr() {
        return usrNr;
    }

    /**
     * Sets the value of the usrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrNr(String value) {
        this.usrNr = value;
    }

    /**
     * Gets the value of the datSrcMnmTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatSrcMnmTe() {
        return datSrcMnmTe;
    }

    /**
     * Sets the value of the datSrcMnmTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatSrcMnmTe(String value) {
        this.datSrcMnmTe = value;
    }

}
