//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}Ctm" minOccurs="0"/>
 *         &lt;element name="DclVlu" type="{upscm}MnyTyp" minOccurs="0"/>
 *         &lt;element name="SmtRefNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShuQy" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="SmtTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}Cod"/>
 *         &lt;element ref="{upscm}IptCod" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ctm",
    "dclVlu",
    "smtRefNr",
    "shuQy",
    "smtTypCd",
    "cod",
    "iptCod"
})
@XmlRootElement(name = "Smt")
@JsonInclude(Include.NON_NULL)
public class Smt {

    @XmlElement(name = "Ctm", namespace = "upscm")
    protected Ctm ctm;
    @XmlElement(name = "DclVlu")
    protected MnyTyp dclVlu;
    @XmlElement(name = "SmtRefNr")
    protected String smtRefNr;
    @XmlElement(name = "ShuQy")
    protected BigInteger shuQy;
    @XmlElement(name = "SmtTypCd")
    protected String smtTypCd;
    @XmlElement(name = "Cod", namespace = "upscm", required = true)
    protected MnyTyp cod;
    @XmlElement(name = "IptCod", namespace = "upscm")
    protected MnyTyp iptCod;

    /**
     * Gets the value of the ctm property.
     * 
     * @return
     *     possible object is
     *     {@link Ctm }
     *     
     */
    public Ctm getCtm() {
        return ctm;
    }

    /**
     * Sets the value of the ctm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ctm }
     *     
     */
    public void setCtm(Ctm value) {
        this.ctm = value;
    }

    /**
     * Gets the value of the dclVlu property.
     * 
     * @return
     *     possible object is
     *     {@link MnyTyp }
     *     
     */
    public MnyTyp getDclVlu() {
        return dclVlu;
    }

    /**
     * Sets the value of the dclVlu property.
     * 
     * @param value
     *     allowed object is
     *     {@link MnyTyp }
     *     
     */
    public void setDclVlu(MnyTyp value) {
        this.dclVlu = value;
    }

    /**
     * Gets the value of the smtRefNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmtRefNr() {
        return smtRefNr;
    }

    /**
     * Sets the value of the smtRefNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmtRefNr(String value) {
        this.smtRefNr = value;
    }

    /**
     * Gets the value of the shuQy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShuQy() {
        return shuQy;
    }

    /**
     * Sets the value of the shuQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShuQy(BigInteger value) {
        this.shuQy = value;
    }

    /**
     * Gets the value of the smtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmtTypCd() {
        return smtTypCd;
    }

    /**
     * Sets the value of the smtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmtTypCd(String value) {
        this.smtTypCd = value;
    }

    /**
     * Gets the value of the cod property.
     * 
     * @return
     *     possible object is
     *     {@link MnyTyp }
     *     
     */
    public MnyTyp getCod() {
        return cod;
    }

    /**
     * Sets the value of the cod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MnyTyp }
     *     
     */
    public void setCod(MnyTyp value) {
        this.cod = value;
    }

    /**
     * Gets the value of the iptCod property.
     * 
     * @return
     *     possible object is
     *     {@link MnyTyp }
     *     
     */
    public MnyTyp getIptCod() {
        return iptCod;
    }

    /**
     * Sets the value of the iptCod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MnyTyp }
     *     
     */
    public void setIptCod(MnyTyp value) {
        this.iptCod = value;
    }

}
