//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}OgzCnyCd"/>
 *         &lt;element ref="{upscm}OgzNr"/>
 *         &lt;element ref="{upscm}SrtTypCd"/>
 *         &lt;element ref="{upscm}AcyDt"/>
 *         &lt;element ref="{upscm}AcyTm" minOccurs="0"/>
 *         &lt;element ref="{upscm}AcyTypCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}UtcTcfTmQy" minOccurs="0"/>
 *         &lt;element ref="{upscm}StsCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}SraCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}PkgLocRlCd" minOccurs="0"/>
 *         &lt;element name="LdCrtDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="SnCpMthCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UsrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}SrtDt" minOccurs="0"/>
 *         &lt;element name="SrtSttTs" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}DatCpMthCgyCd"/>
 *       &lt;attribute ref="{upscm}DatCpInfSrcCd"/>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ogzCnyCd",
    "ogzNr",
    "srtTypCd",
    "acyDt",
    "acyTm",
    "acyTypCd",
    "utcTcfTmQy",
    "stsCd",
    "sraCd",
    "pkgLocRlCd",
    "ldCrtDt",
    "snCpMthCd",
    "usrNr",
    "srtDt",
    "srtSttTs"
})
@XmlRootElement(name = "SnAcy")
@JsonInclude(Include.NON_NULL)
public class SnAcy {

    @XmlElement(name = "OgzCnyCd", namespace = "upscm", required = true)
    protected String ogzCnyCd;
    @XmlElement(name = "OgzNr", namespace = "upscm", required = true)
    protected String ogzNr;
    @XmlElement(name = "SrtTypCd", namespace = "upscm", required = true)
    protected String srtTypCd;
    @XmlElement(name = "AcyDt", namespace = "upscm", required = true)
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String acyDt;
    @XmlElement(name = "AcyTm", namespace = "upscm")
    @XmlSchemaType(name = "time")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="HH:mm:ss")
    protected String acyTm;
    @XmlElement(name = "AcyTypCd", namespace = "upscm")
    protected String acyTypCd;
    @XmlElement(name = "UtcTcfTmQy", namespace = "upscm")
    protected String utcTcfTmQy;
    @XmlElement(name = "StsCd", namespace = "upscm")
    protected String stsCd;
    @XmlElement(name = "SraCd", namespace = "upscm")
    protected String sraCd;
    @XmlElement(name = "PkgLocRlCd", namespace = "upscm")
    protected String pkgLocRlCd;
    @XmlElement(name = "LdCrtDt")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String ldCrtDt;
    @XmlElement(name = "SnCpMthCd")
    protected String snCpMthCd;
    @XmlElement(name = "UsrNr")
    protected String usrNr;
    @XmlElement(name = "SrtDt", namespace = "upscm")
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String srtDt;
    @XmlElement(name = "SrtSttTs")
    @XmlSchemaType(name = "dateTime")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss")
    protected String srtSttTs;
    @XmlAttribute(name = "DatCpMthCgyCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpMthCgyCd;
    @XmlAttribute(name = "DatCpInfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpInfSrcCd;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the ogzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzCnyCd() {
        return ogzCnyCd;
    }

    /**
     * Sets the value of the ogzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzCnyCd(String value) {
        this.ogzCnyCd = value;
    }

    /**
     * Gets the value of the ogzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzNr() {
        return ogzNr;
    }

    /**
     * Sets the value of the ogzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzNr(String value) {
        this.ogzNr = value;
    }

    /**
     * Gets the value of the srtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypCd() {
        return srtTypCd;
    }

    /**
     * Sets the value of the srtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypCd(String value) {
        this.srtTypCd = value;
    }

    /**
     * Gets the value of the acyDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAcyDt() {
        return acyDt;
    }

    /**
     * Sets the value of the acyDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcyDt(String value) {
        this.acyDt = value;
    }

    /**
     * Gets the value of the acyTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAcyTm() {
        return acyTm;
    }

    /**
     * Sets the value of the acyTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcyTm(String value) {
        this.acyTm = value;
    }

    /**
     * Gets the value of the acyTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcyTypCd() {
        return acyTypCd;
    }

    /**
     * Sets the value of the acyTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcyTypCd(String value) {
        this.acyTypCd = value;
    }

    /**
     * Gets the value of the utcTcfTmQy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtcTcfTmQy() {
        return utcTcfTmQy;
    }

    /**
     * Sets the value of the utcTcfTmQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtcTcfTmQy(String value) {
        this.utcTcfTmQy = value;
    }

    /**
     * Gets the value of the stsCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * Sets the value of the stsCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStsCd(String value) {
        this.stsCd = value;
    }

    /**
     * Gets the value of the sraCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSraCd() {
        return sraCd;
    }

    /**
     * Sets the value of the sraCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSraCd(String value) {
        this.sraCd = value;
    }

    /**
     * Gets the value of the pkgLocRlCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkgLocRlCd() {
        return pkgLocRlCd;
    }

    /**
     * Sets the value of the pkgLocRlCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkgLocRlCd(String value) {
        this.pkgLocRlCd = value;
    }

    /**
     * Gets the value of the ldCrtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getLdCrtDt() {
        return ldCrtDt;
    }

    /**
     * Sets the value of the ldCrtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLdCrtDt(String value) {
        this.ldCrtDt = value;
    }

    /**
     * Gets the value of the snCpMthCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnCpMthCd() {
        return snCpMthCd;
    }

    /**
     * Sets the value of the snCpMthCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnCpMthCd(String value) {
        this.snCpMthCd = value;
    }

    /**
     * Gets the value of the usrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrNr() {
        return usrNr;
    }

    /**
     * Sets the value of the usrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrNr(String value) {
        this.usrNr = value;
    }

    /**
     * Gets the value of the srtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getSrtDt() {
        return srtDt;
    }

    /**
     * Sets the value of the srtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSrtDt(String value) {
        this.srtDt = value;
    }

    /**
     * Gets the value of the srtSttTs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getSrtSttTs() {
        return srtSttTs;
    }

    /**
     * Sets the value of the srtSttTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSrtSttTs(String value) {
        this.srtSttTs = value;
    }

    /**
     * Gets the value of the datCpMthCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpMthCgyCd() {
        return datCpMthCgyCd;
    }

    /**
     * Sets the value of the datCpMthCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpMthCgyCd(String value) {
        this.datCpMthCgyCd = value;
    }

    /**
     * Gets the value of the datCpInfSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpInfSrcCd() {
        return datCpInfSrcCd;
    }

    /**
     * Sets the value of the datCpInfSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpInfSrcCd(String value) {
        this.datCpInfSrcCd = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
