//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for WgtTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WgtTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}MsuCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}MsuDscTe" minOccurs="0"/>
 *         &lt;element ref="{upscm}MsuMnmTe" minOccurs="0"/>
 *         &lt;element ref="{upscm}Qy" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}InfDtTm"/>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WgtTyp", propOrder = {
    "msuCd",
    "msuDscTe",
    "msuMnmTe",
    "qy"
})
@JsonInclude(Include.NON_NULL)
public class WgtTyp {

    @XmlElement(name = "MsuCd", namespace = "upscm")
    protected String msuCd;
    @XmlElement(name = "MsuDscTe", namespace = "upscm")
    protected String msuDscTe;
    @XmlElement(name = "MsuMnmTe", namespace = "upscm")
    protected String msuMnmTe;
    @XmlElement(name = "Qy", namespace = "upscm")
    protected BigDecimal qy;
    @XmlAttribute(name = "InfDtTm", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infDtTm;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the msuCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsuCd() {
        return msuCd;
    }

    /**
     * Sets the value of the msuCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsuCd(String value) {
        this.msuCd = value;
    }

    /**
     * Gets the value of the msuDscTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsuDscTe() {
        return msuDscTe;
    }

    /**
     * Sets the value of the msuDscTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsuDscTe(String value) {
        this.msuDscTe = value;
    }

    /**
     * Gets the value of the msuMnmTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsuMnmTe() {
        return msuMnmTe;
    }

    /**
     * Sets the value of the msuMnmTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsuMnmTe(String value) {
        this.msuMnmTe = value;
    }

    /**
     * Gets the value of the qy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQy() {
        return qy;
    }

    /**
     * Sets the value of the qy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQy(BigDecimal value) {
        this.qy = value;
    }

    /**
     * Gets the value of the infDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfDtTm() {
        return infDtTm;
    }

    /**
     * Sets the value of the infDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfDtTm(String value) {
        this.infDtTm = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
