//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 12:54:31 AM GMT+05:30 
//


package com.rajantech.camel.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{upscm}AcyDt"/>
 *         &lt;element ref="{upscm}AcyTm" minOccurs="0"/>
 *         &lt;element ref="{upscm}UtcTcfTmQy" minOccurs="0"/>
 *         &lt;element ref="{upscm}OgzCnyCd"/>
 *         &lt;element ref="{upscm}OgzNr"/>
 *         &lt;element ref="{upscm}SrtTypCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}Dcv" minOccurs="0"/>
 *         &lt;element ref="{upscm}Rpt" minOccurs="0"/>
 *         &lt;element name="RptOgzCnyCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RptOgzNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{upscm}FacCnyCd" minOccurs="0"/>
 *         &lt;element ref="{upscm}FacMnmTe" minOccurs="0"/>
 *         &lt;element ref="{upscm}FacLocNr" minOccurs="0"/>
 *         &lt;element name="XcpStsCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="XcpSraCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="XcpStsRlvCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="XcpIr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UsrNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{upscm}DatCpMthCgyCd"/>
 *       &lt;attribute ref="{upscm}DatCpInfSrcCd"/>
 *       &lt;attribute ref="{upscm}InfSrcCd"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acyDt",
    "acyTm",
    "utcTcfTmQy",
    "ogzCnyCd",
    "ogzNr",
    "srtTypCd",
    "dcv",
    "rpt",
    "rptOgzCnyCd",
    "rptOgzNr",
    "facCnyCd",
    "facMnmTe",
    "facLocNr",
    "xcpStsCd",
    "xcpSraCd",
    "xcpStsRlvCd",
    "xcpIr",
    "usrNr"
})
@XmlRootElement(name = "XcpAcy")
@JsonInclude(Include.NON_NULL)
public class XcpAcy {

    @XmlElement(name = "AcyDt", namespace = "upscm", required = true)
    @XmlSchemaType(name = "date")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    protected String acyDt;
    @XmlElement(name = "AcyTm", namespace = "upscm")
    @XmlSchemaType(name = "time")
    //@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="HH:mm:ss")
    protected String acyTm;
    @XmlElement(name = "UtcTcfTmQy", namespace = "upscm")
    protected String utcTcfTmQy;
    @XmlElement(name = "OgzCnyCd", namespace = "upscm", required = true)
    protected String ogzCnyCd;
    @XmlElement(name = "OgzNr", namespace = "upscm", required = true)
    protected String ogzNr;
    @XmlElement(name = "SrtTypCd", namespace = "upscm")
    protected String srtTypCd;
    @XmlElement(name = "Dcv", namespace = "upscm")
    protected OgzDtTmTyp dcv;
    @XmlElement(name = "Rpt", namespace = "upscm")
    protected OgzDtTmTyp rpt;
    @XmlElement(name = "RptOgzCnyCd")
    protected String rptOgzCnyCd;
    @XmlElement(name = "RptOgzNr")
    protected String rptOgzNr;
    @XmlElement(name = "FacCnyCd", namespace = "upscm")
    protected String facCnyCd;
    @XmlElement(name = "FacMnmTe", namespace = "upscm")
    protected String facMnmTe;
    @XmlElement(name = "FacLocNr", namespace = "upscm")
    protected String facLocNr;
    @XmlElement(name = "XcpStsCd")
    protected String xcpStsCd;
    @XmlElement(name = "XcpSraCd")
    protected String xcpSraCd;
    @XmlElement(name = "XcpStsRlvCd")
    protected String xcpStsRlvCd;
    @XmlElement(name = "XcpIr")
    protected Boolean xcpIr;
    @XmlElement(name = "UsrNr")
    protected String usrNr;
    @XmlAttribute(name = "DatCpMthCgyCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpMthCgyCd;
    @XmlAttribute(name = "DatCpInfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String datCpInfSrcCd;
    @XmlAttribute(name = "InfSrcCd", namespace = "upscm")
    @XmlSchemaType(name = "anySimpleType")
    protected String infSrcCd;

    /**
     * Gets the value of the acyDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAcyDt() {
        return acyDt;
    }

    /**
     * Sets the value of the acyDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcyDt(String value) {
        this.acyDt = value;
    }

    /**
     * Gets the value of the acyTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getAcyTm() {
        return acyTm;
    }

    /**
     * Sets the value of the acyTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcyTm(String value) {
        this.acyTm = value;
    }

    /**
     * Gets the value of the utcTcfTmQy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtcTcfTmQy() {
        return utcTcfTmQy;
    }

    /**
     * Sets the value of the utcTcfTmQy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtcTcfTmQy(String value) {
        this.utcTcfTmQy = value;
    }

    /**
     * Gets the value of the ogzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzCnyCd() {
        return ogzCnyCd;
    }

    /**
     * Sets the value of the ogzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzCnyCd(String value) {
        this.ogzCnyCd = value;
    }

    /**
     * Gets the value of the ogzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgzNr() {
        return ogzNr;
    }

    /**
     * Sets the value of the ogzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgzNr(String value) {
        this.ogzNr = value;
    }

    /**
     * Gets the value of the srtTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtTypCd() {
        return srtTypCd;
    }

    /**
     * Sets the value of the srtTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtTypCd(String value) {
        this.srtTypCd = value;
    }

    /**
     * Gets the value of the dcv property.
     * 
     * @return
     *     possible object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public OgzDtTmTyp getDcv() {
        return dcv;
    }

    /**
     * Sets the value of the dcv property.
     * 
     * @param value
     *     allowed object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public void setDcv(OgzDtTmTyp value) {
        this.dcv = value;
    }

    /**
     * Gets the value of the rpt property.
     * 
     * @return
     *     possible object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public OgzDtTmTyp getRpt() {
        return rpt;
    }

    /**
     * Sets the value of the rpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OgzDtTmTyp }
     *     
     */
    public void setRpt(OgzDtTmTyp value) {
        this.rpt = value;
    }

    /**
     * Gets the value of the rptOgzCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOgzCnyCd() {
        return rptOgzCnyCd;
    }

    /**
     * Sets the value of the rptOgzCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOgzCnyCd(String value) {
        this.rptOgzCnyCd = value;
    }

    /**
     * Gets the value of the rptOgzNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOgzNr() {
        return rptOgzNr;
    }

    /**
     * Sets the value of the rptOgzNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOgzNr(String value) {
        this.rptOgzNr = value;
    }

    /**
     * Gets the value of the facCnyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacCnyCd() {
        return facCnyCd;
    }

    /**
     * Sets the value of the facCnyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacCnyCd(String value) {
        this.facCnyCd = value;
    }

    /**
     * Gets the value of the facMnmTe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacMnmTe() {
        return facMnmTe;
    }

    /**
     * Sets the value of the facMnmTe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacMnmTe(String value) {
        this.facMnmTe = value;
    }

    /**
     * Gets the value of the facLocNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacLocNr() {
        return facLocNr;
    }

    /**
     * Sets the value of the facLocNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacLocNr(String value) {
        this.facLocNr = value;
    }

    /**
     * Gets the value of the xcpStsCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXcpStsCd() {
        return xcpStsCd;
    }

    /**
     * Sets the value of the xcpStsCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXcpStsCd(String value) {
        this.xcpStsCd = value;
    }

    /**
     * Gets the value of the xcpSraCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXcpSraCd() {
        return xcpSraCd;
    }

    /**
     * Sets the value of the xcpSraCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXcpSraCd(String value) {
        this.xcpSraCd = value;
    }

    /**
     * Gets the value of the xcpStsRlvCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXcpStsRlvCd() {
        return xcpStsRlvCd;
    }

    /**
     * Sets the value of the xcpStsRlvCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXcpStsRlvCd(String value) {
        this.xcpStsRlvCd = value;
    }

    /**
     * Gets the value of the xcpIr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXcpIr() {
        return xcpIr;
    }

    /**
     * Sets the value of the xcpIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXcpIr(Boolean value) {
        this.xcpIr = value;
    }

    /**
     * Gets the value of the usrNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrNr() {
        return usrNr;
    }

    /**
     * Sets the value of the usrNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrNr(String value) {
        this.usrNr = value;
    }

    /**
     * Gets the value of the datCpMthCgyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpMthCgyCd() {
        return datCpMthCgyCd;
    }

    /**
     * Sets the value of the datCpMthCgyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpMthCgyCd(String value) {
        this.datCpMthCgyCd = value;
    }

    /**
     * Gets the value of the datCpInfSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatCpInfSrcCd() {
        return datCpInfSrcCd;
    }

    /**
     * Sets the value of the datCpInfSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatCpInfSrcCd(String value) {
        this.datCpInfSrcCd = value;
    }

    /**
     * Gets the value of the infSrcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfSrcCd() {
        return infSrcCd;
    }

    /**
     * Sets the value of the infSrcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfSrcCd(String value) {
        this.infSrcCd = value;
    }

}
